name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t umaiwa9/simple-node-app:latest ./backend

    - name: Push Docker Image to Docker Hub
      run: |
        docker login -u umaiwa9 -p ${{ secrets.DOCKER_PASSWORD }}
        docker tag umaiwa9/simple-node-app umaiwa9/simple-node-app:latest
        docker push umaiwa9/simple-node-app:latest
  deploy:
    runs-on: self-hosted
    needs: build-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        kubectl config use-context minikube
        
    - name: Deploy to Minikube
      run: |
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
        kubectl rollout restart deployment node-app
        kubectl rollout status deployment node-app